### ISSUE TITLE
Mockups in Figma : Fix mockups flaws and harmonize design

### ISSUE THREAD

**Issue by ForestDope** [WanderPals/WanderPals#170]
Fix several wrong designs in mockups made by others + harmonized the design to be consistent.

**Comment by annhit29** [comment]
There was a bug in the arrival screen : the bottom nav bar wasn't displayed because it was outside the arrival screen.
To fix it, we simply need to put the bottom nav bar inside the arrival screen and then the bottom nav bar is now included in the arrival screen, so everything is well displayed now when we close the search bar, as shown in the second image which is the arrival screen.

![on](https://github.com/WanderPals/WanderPals/assets/64964377/8be3c580-c467-45cc-99b5-eb137a61ea7e)
![off](https://github.com/WanderPals/WanderPals/assets/64964377/de52e4b4-4c40-40c3-a185-3abaa599552d)

**Comment by annhit29** [comment]
Another bug that I just fixed is that the on off tab was behind, so I bring it in front, and so it is visible now on the design now
![image](https://github.com/WanderPals/WanderPals/assets/64964377/42664d01-f6a5-40f3-86de-f206e213f749)
